### ISSUE TITLE
"The 'repo_token' variable is empty." on PR Runs of Scorecard Action

### ISSUE THREAD

**Issue by nibanks** [ossf/scorecard-action#109] opened 2022-02-19 16:36 UTC
I believe https://github.com/ossf/scorecard-action/pull/71 regressed PR runs of scorecard, where we don't actually need the repo_token because we aren't pushing the results, just checking them:

https://github.com/microsoft/msquic/runs/5259593124?check_suite_focus=true

**Comment by laurentsimon** [comment] 2022-02-22 16:26
Thanks for the report.
Fyi, we have not advertised support for pull request yet (it's not in the workflow example we provide). This should have been clearer from us. 
The token is used for two reason:
1. to access GitHubAPIs - in this case you're right it's not needed. I think the checkout should not need the token. But I wonder if GitHub may still require one sometimes?
2. Uploading the results as SARIF is still performed, and that's how the GitHub UI manages to show fixed and/or additional results introduced by the given PR.

We will try to add PR support in the next release.

**Comment by nibanks** [comment] 2022-03-05 15:11
@laurentsimon any idea on when you might add PR support? I will be blocking dependabot updates (i.e. [this PR](https://github.com/microsoft/msquic/pull/2412)) for this action until I can safely merge the latest without breaking our existing behavior.

**Comment by nibanks** [comment] 2022-03-07 16:15
Why is that necessary? As you mentioned in your (1) above no token should be necessary since you'd just be querying state, not publishing anything for PRs.

**Comment by dthaler** [comment] 2022-03-28 20:08
ebpf-for-windows project is now also blocked updating beyond 1.0.3 due to this issue.

**Comment by laurentsimon** [comment] 2022-03-28 20:17
@dthaler have you tested with v1.0.4?

**Comment by dthaler** [comment] 2022-03-28 20:42
> @dthaler have you tested with v1.0.4?

Yes, we see intermittant failures, such as in https://github.com/microsoft/ebpf-for-windows/runs/5726574449?check_suite_focus=true (whereas https://github.com/microsoft/ebpf-for-windows/runs/5725496349?check_suite_focus=true passed referencing the same commit)

**Comment by laurentsimon** [comment] 2022-03-28 21:57
Great finding, intermittent problems, that's really interesting. Could you use this PR's branch (my personal repo) to add logs to the action? I think we may be able to point out the problems with this additional log - just this file https://github.com/ossf/scorecard-action/pull/155/files#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2

**Comment by dthaler** [comment] 2022-04-04 15:28
FYI, in the ebpf-for-windows project, I used `dependabot ignore this minor version` to block upgrading the scorecard-action from 1.0.3 until this issue is fixed or 1.1 comes out, since the PR to upgrade to 1.0.3 was accidentally merged and everything started failing and had to be reverted.

**Comment by laurentsimon** [comment] 2022-04-04 22:24
I'l spend some time to reproduce the problem soon.

**Comment by dthaler** [comment] 2022-09-13 16:48
@laurentsimon 
> We will try to add PR support in the next release.

Now that v2.0 is out, is there any progress on fixing this PR?

**Comment by laurentsimon** [comment] 2022-09-13 17:56
Not officially supported yet, but I think it should work if you use
```
publish_results: ${{ github.event_name != 'pull_request' }}
```

I will create a PR to have the equivalent of `${{ github.event_name != 'pull_request' }}` in the code.

**Closed** 2022-09-13 18:35 UTC
